### ISSUE TITLE
Futures consumer example no longer works with 0.15

### ISSUE THREAD

**Issue by jenshnielsen** [sozu-proxy/lapin#151]
The example in https://github.com/sozu-proxy/lapin/blob/master/futures/README.md#creating-a-consumer as of a5bf90043697d46c7a534d1af36023de8c1211c3 no longer seems to work with 0.15 

```
error[E0271]: type mismatch resolving `<impl std::marker::Send+futures::future::Future as futures::future::IntoFuture>::Error == std::io::Error`
  --> src\main.rs:26:18
   |
26 |                 .and_then(|stream| {
   |                  ^^^^^^^^ expected struct `lapin_futures::error::Error`, found struct `std::io::Error`
   |
   = note: expected type `lapin_futures::error::Error`
              found type `std::io::Error`

error[E0599]: no method named `and_then` found for type `futures::future::and_then::AndThen<tokio_tcp::stream::ConnectFuture, impl std::marker::Send+futures::future::Future, [closure@src\main.rs:26:27: 30:18]>` in the current scope
  --> src\main.rs:31:18
   |
31 |                 .and_then(|(client, heartbeat)| {
   |                  ^^^^^^^^
   |
   = note: the method `and_then` exists but the following trait bounds were not satisfied:
           `futures::future::and_then::AndThen<tokio_tcp::stream::ConnectFuture, impl std::marker::Send+futures::future::Future, [closure@src\main.rs:26:27: 30:18]> : futures::future::Future`
           `&mut futures::future::and_then::AndThen<tokio_tcp::stream::ConnectFuture, impl std::marker::Send+futures::future::Future, [closure@src\main.rs:26:27: 30:18]> : futures::stream::Stream`
           `&mut futures::future::and_then::AndThen<tokio_tcp::stream::ConnectFuture, impl std::marker::Send+futures::future::Future, [closure@src\main.rs:26:27: 30:18]> : futures::future::Future`

error: aborting due to 2 previous errors

Some errors occurred: E0271, E0599.
For more information about an error, try `rustc --explain E0271`.
error: Could not compile `rmq_sqlite`.

To learn more, run the command again with --verbose.
```

It compiles correctly with 0.14.1

**Comment by Keruspe** [comment]
Heh, I indeed forgot to update the README.

The example from the examples/ directory works fine if your want to
contribute by fixing the README :)

I’ll fix it soon-ish otherwise

**Comment by jenshnielsen** [comment]
Thanks, Is it the intention that the readme example should match the example in the examples dir or should it just be updated to map the errors appropriately

**Comment by Keruspe** [comment]
They are supposed to match, yes

**Comment by jlgerber** [comment]
Unfortunately, the examples in lapin/futures are not a good substitute for the simple example in the README. Specifically, the client.rs example is actually both a client and server. For those of us trying to come to terms with async style nesting/chaining, this is more complicated than needs be.

Case in point, I tried to separate the two, cutting out the message consumption in the client, and creating a server.rs which cuts out the message production. And this works, however, neither of the executables exit when done. That is expected behavior for a server, but not for a client I warrant. 

I know that the answer is probably somewhere in the tokio documentation. However, it would be great to add termination to the example client.

Also, it would be fantastic if there was some discussion in the docs of how one would use the client code in production. Would this run in a separate thread using message passing from the rest of the client? Or would one go through the whole process outlined for each message? 

Anyway, thank you for the excellent crate!

**Comment by Keruspe** [comment]
Will fix tomorrow

**Comment by Keruspe** [comment]
Wrt termination, you have to cancel the heartbeat using the heartbeat handle

**Comment by Keruspe** [comment]
Btw, that’s just terminology but both are clients, just a producer client and a consumer client, but no server there

**Comment by jlgerber** [comment]
> Wrt termination, you have to cancel the heartbeat using the heartbeat handle

Ahh. Thank you.

**Comment by Relrin** [comment]
Any plans to update other example from lapin-futures ([consumers.rs](https://github.com/sozu-proxy/lapin/blob/master/futures/examples/consumers.rs) and [topic.rs](https://github.com/sozu-proxy/lapin/blob/master/futures/examples/topic.rs)) directory?

First of all because it will reflect the actual state of the lapin-futures crate (probably to lapin-async it applies as well). In addition to it that will be really helpful for case when someone wants to port code after breaking changes around `Error`/`ErrorKind` starting from the `0.15.0` release.

**Comment by Keruspe** [comment]
@Relrin those are already up to date, only the README is not, and I'm currently fixing it
